### ISSUE TITLE
CRITICAL - FromEntity(entity * Problem

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-logging#4]
**"CRITICAL"** @Sddilora @Feyzanrs 

I have found a bug. "FromEntity(entity *"
gRPC DTOs of our system have New{ANY}FromEntity functions. That takes the pointer of the entity. If the entity has any pointer field all entity pointer fields would be the same when using New{ANY}FromEntities.

We have to change all "FromEntity(entity *" to "FromEntity(entity " and fix all calls in all projects.

Please open this issue in all repositories of the backend.

**Comment by Sddilora** [comment]
> FromEntity(entity *

I couldn't be sure about the part to be fixed.

```go
NewLogDataFromEntity(entity *me.LogData) //  causes bug
NewLogDataFromEntity(entity me.LogData) // fixed
```
Is that right ?

**Comment by husamettinarabaci** [comment]
I think it will be a good solution.

**Comment by Sddilora** [comment]
Pay close attention to where this function is called, ensuring that parameters are passed without the use of pointers.
![Screenshot from 2024-03-16 23-16-12](https://github.com/octoposprime/op-be-user/assets/122971619/8228390c-5232-493a-9f8f-b72db2d64d2d)

**Comment by furkanadiiguzel** [comment]
What about these mistakes ? Am I going to change these too or do we have another solution for them ?
<img width="826" alt="Screenshot 2024-03-17 at 16 32 25" src="https://github.com/octoposprime/op-be-logging/assets/101877734/db13e380-2e1d-4562-b6e9-977a1e8952d9">
<img width="827" alt="Screenshot 2024-03-17 at 16 34 17" src="https://github.com/octoposprime/op-be-logging/assets/101877734/1a3a86f3-76f9-4861-9ef6-ef9a38347d22">

**Comment by Sddilora** [comment]
Yes of course they need to be handled, https://github.com/octoposprime/op-be-user/issues/14#issuecomment-2002117374

**Comment by Sddilora** [comment]
Can be closed after 
- [x] [Handle Logging Service](https://github.com/octoposprime/op-be-logging/issues/4)
- [X] [Handle User Service](https://github.com/octoposprime/op-be-user/issues/14)
